### ISSUE TITLE
Optional route segments

### ISSUE THREAD

**Issue by carl-berg** [mattiasnordqvist/Web-Anchor#101]
Would be nice to be able to insert a route segment optionally. Consider this api
```
[BaseLocation("api/{version}")]
public interface IUserApi
{
    [Get("user")]
    Task<UserResult> GetUser([Header("Authorization")] string bearer);
}
```
If `version=v1` you would get `api/v1/user`
... but if `version=""`, you would get `api//user` so it would be nice if that could be handled somehow by WebAnchor

**Comment by mattiasnordqvist** [comment]
Are we happy with just repeating execution of Replace("//", "/") until there's no "//" left, or will that break anything?

**Comment by carl-berg** [comment]
It could potentially break something i guess if someone is actually using // in a url, but is that even valid?

**Comment by mattiasnordqvist** [comment]
my browser accepts it. Let's just make it opt-in

**Comment by mattiasnordqvist** [comment]
this issue kind of also raises the question about what should happen if a route segment value is null.

**Comment by mattiasnordqvist** [comment]
Also, about normalizing urls. We could implement a lot of stuff:
https://en.wikipedia.org/wiki/URI_normalization

**Comment by mattiasnordqvist** [comment]
There ya go!

**Comment by mattiasnordqvist** [comment]
@all-contributors please add @carl-berg for bug reports
