### ISSUE TITLE
Options to ignore cache

### ISSUE THREAD

**Issue by mattiasnordqvist** [mattiasnordqvist/Web-Anchor#16]
Pretty much like http://stackoverflow.com/questions/4303829/how-to-prevent-a-jquery-ajax-request-from-caching-in-internet-explorer

Consider adding this feature as a built-in feature.

Do this by adding an extra parameter with some random value to a web api call.

This could be done in 2 ways. Both should be possible. An added Transformer which adds the random value to all calls. This transformer could be toggled with settings for HttpRequestFactory

Also create an attribute, that could be used to add this behaviour to selected methods or whole Apis.

**Comment by mattiasnordqvist** [comment]
Should also include test on the parameter transformer
And documentation

**Comment by mattiasnordqvist** [comment]
Is this even needed for HttpClient? I'm not sure about how it works. Will this sometimes help getting around caches on routers? How about servers? @carl-berg

**Comment by carl-berg** [comment]
The ajax version i think is about forcing the browser not to chache requests. This doesn't seem as useful in the case of WebAnchor. I'd say we hold off on this until we have a case for it. It's easy enough to implement on your own.

**Comment by mattiasnordqvist** [comment]
Already fried this one. :)

**Comment by mattiasnordqvist** [comment]
Frying this fish actually introduced a new concept. I think it was a good addition. I had to create a TransformerAttribute-type, that can be applied on api- or method-level.

**Comment by carl-berg** [comment]
:+1: I was actually thinking that was something you might want to set at an Api-level, not application wide.

**Comment by mattiasnordqvist** [comment]
This functionality is hidden for now. We may not need it so let's not bother writing tests or documentation for it just yet. I'm removing this issue from the version 1 - milestone

**Comment by mattiasnordqvist** [comment]
Closing this until we find use for it.
