### ISSUE TITLE
Support HTTP multipart request

### ISSUE THREAD

**Issue by mattiasnordqvist** [mattiasnordqvist/Web-Anchor#19]
So that we can use WebAnchor to upload files. RestSharp and ReFit does it so we should too

**Comment by mattiasnordqvist** [comment]
From http://stackoverflow.com/questions/566462/upload-files-with-httpwebrequest-multipart-form-data

```csharp
// Perform the equivalent of posting a form with a filename and two files, in HTML:
// <form action="{url}" method="post" enctype="multipart/form-data">
//     <input type="text" name="filename" />
//     <input type="file" name="file1" />
//     <input type="file" name="file2" />
// </form>
private System.IO.Stream Upload(string url, string filename, Stream fileStream, byte [] fileBytes)
{
    // Convert each of the three inputs into HttpContent objects

    HttpContent stringContent = new StringContent(filename);
    // examples of converting both Stream and byte [] to HttpContent objects
    // representing input type file
    HttpContent fileStreamContent = new StreamContent(fileStream);
    HttpContent bytesContent = new ByteArrayContent(fileBytes);

    // Submit the form using HttpClient and 
    // create form data as Multipart (enctype="multipart/form-data")

    using (var client = new HttpClient())
    using (var formData = new MultipartFormDataContent()) 
    {
        // Add the HttpContent objects to the form data

        // <input type="text" name="filename" />
        formData.Add(stringContent, "filename", "filename");
        // <input type="file" name="file1" />
        formData.Add(fileStreamContent, "file1", "file1");
        // <input type="file" name="file2" />
        formData.Add(bytesContent, "file2", "file2");

        // Actually invoke the request to the server

        // equivalent to (action="{url}" method="post")
        var response = client.PostAsync(url, formData).Result;

        // equivalent of pressing the submit button on the form
        if (!response.IsSuccessStatusCode)
        {
            return null;
        }
        return response.Content.ReadAsStreamAsync().Result;
    }
}
```

**Comment by mikegoatly** [comment]
Hi @mattiasnordqvist I'm going to need this shortly so I'll look at adding it in - I assume this is still up-for-grabs?

**Comment by mattiasnordqvist** [comment]
Nice @mikegoatly ! 👍 Your PR is very much appreciated! I'll take a look at it. If there's any parts we disagree on there is always a possibility to release your multipart support as a pre-release, while we take time to set the final implementation. (So that you won't get stuck)

**Comment by mattiasnordqvist** [comment]
Currently released in 6.2.0-pre1.

**Comment by mattiasnordqvist** [comment]
I don't know why but our new multipart-tests fail in our appveyor-build.
Appveyor says that this Regex and this Value does not match. It works on my computer though. 😎 
Havn't looked into it really, but the regexp looks ok to me.

```csharp

Regex: --(?<id>[0-9a-f\-]*)
Content-Type: text/plain
Content-Disposition: form-data; name=Field1; filename=test\.txt; filename\*=utf-8''test\.txt
From bytes
--\k<id>--


Value: --2e29b05e-5fb9-47dd-bc11-63503c711c73
Content-Type: text/plain
Content-Disposition: form-data; name=Field1; filename=test.txt; filename*=utf-8''test.txt
From bytes
--2e29b05e-5fb9-47dd-bc11-63503c711c73--

```

**Comment by mikegoatly** [comment]
Interesting... I'll take a look in a bit.

**Comment by mikegoatly** [comment]
I think it must have something to do with whitespace - the tests fail for me locally and the regex fails in resharper's regex validator, but if I remove and replace the line endings one by one, the regex gradually passes. I'll look to see if I can find a better way of testing that doesn't involve the regex.

**Comment by mattiasnordqvist** [comment]
So was my thinkg too. Whitespaces or newlines. Hard to test without pushing new code to the build server. :(

**Comment by mikegoatly** [comment]
Ok, so looking at the source in notepad++, I see only LF's at the line ends:
![image](https://user-images.githubusercontent.com/4577868/36274942-457c2d2a-1281-11e8-8600-8d3a4bd8e43a.png)

The request body is formatted with CR/LF, hence the failure

**Comment by mikegoatly** [comment]
I suspect it's a git setting some where that's converting line endings, but rather than battle with that this will unblock us for now

**Comment by mattiasnordqvist** [comment]
It works nicely @mikegoatly. Thank you very much! :)

**Comment by mikegoatly** [comment]
Glad to help!
