### ISSUE TITLE
Use dynamic as response type

### ISSUE THREAD

**Issue by mattiasnordqvist** [mattiasnordqvist/Web-Anchor#23]
... for extremely quick setup?

**Comment by carl-berg** [comment]
It could be useful i guess if you're rapidly prototyping a concept but don't want to keep refactoring your models?

**Comment by mattiasnordqvist** [comment]
That's what I'm thinking. For no-ceremony kind of setup. Would be nice also to be able to use anonymous types as payload for put and post, but I think that is actually already possible.

**Comment by mattiasnordqvist** [comment]
test on anonymous types as content added. Seems to work

**Comment by mattiasnordqvist** [comment]
Wait for #43

**Comment by mattiasnordqvist** [comment]
This is kind of already possible.
Declare your method return type as Task\<ExpandoObject\>
use it like var dynamix = api.Get();
