### ISSUE TITLE
Allow primitives and string as body content

### ISSUE THREAD

**Issue by mattiasnordqvist** [mattiasnordqvist/Web-Anchor#31]
For example, just a string could be translated to

```
{
    paramName: value
}
```

**Comment by mattiasnordqvist** [comment]
Now... should we really?

Consult this: http://stackoverflow.com/questions/13318420/json-standard-a-single-string-value

But maybe we should allow lists as well as dictionaries?

**Comment by carl-berg** [comment]
Not sure i follow... `{ paramName: value }`, is this not valid JSON? Or do you mean that the user would expect it to be sent with just the value as body? Because that would not be possible either with _JSON_ or _x-www-form-urlencoded_ right?

**Comment by mattiasnordqvist** [comment]
Sorry for being unclear. Yes,  ```{ paramName: value }``` is of course valid json. It seems many people expect a single value, líke "a value" to be valid json, When I consult both the ECMA 404 and the RFC7159, they are both a bit vague about this. However, the RFC spec says: "A JSON value MUST be an object, array, number, or string, or one of the following three literal names: false null true". So the question is, should be we allow all json values or only json objects and possibly arrays. What does the _Content-type: application/json_ say about it? I really can't find any good information on it. So then i headed over to http://jsonlint.com/ and tested it. My conclusion is that a single value  should not be allowed as body. The question, then, is 1) if we should provide this convenience of automatically wrapping primitives in an object, or if we should throw an exception. I vote for exception. The user is always able to override the behaviour of the bodyserializer himself if he really needs to. And 2) does web anchor handle lists as root elements at this time? Otherwise, we should make sure it does.

**Comment by carl-berg** [comment]
Myself i'd prefer to have them wrapped automatically as any other way would not be possible, but i guess i can always write a custom serializer to handle that.

**Comment by mattiasnordqvist** [comment]
Let's discuss this on friday. :)

**Comment by mattiasnordqvist** [comment]
I think this is considered valid json nowadays

**Comment by mattiasnordqvist** [comment]
No-one needed this is 3 years so I think it's safe to close...
