### ISSUE TITLE
ToDictionary-extension-method fails on dates and arrays

### ISSUE THREAD

**Issue by mattiasnordqvist** [mattiasnordqvist/Web-Anchor#38]
``` csharp
[Test]
public void TestDate()
{
    var now = DateTime.UtcNow;
    var d = new { Timestamp = now }.ToDictionary();
    Assert.AreEqual(now, d["Timestamp"]);
}
```

**Comment by carl-berg** [comment]
Same behavior from arrays...
```
var packagedArray = new { MyArray = new int[0] }.ToDictionary();
```

**Comment by mattiasnordqvist** [comment]
Generally, ToDictionary() will fail on all objekts that have circular references.

**Comment by mattiasnordqvist** [comment]
We should write some tests like this:

[Test]
public void TestToDictionary_xxx()
{
    var now = DateTime.UtcNow;
    var d = CreateJson(new { Timestamp = now }.ToDictionary());
    var d2 = CreateJson(new { Timestamp = now });
    Assert.AreEqual(d, d2);
}

**Comment by mattiasnordqvist** [comment]
Since this feature is no longer enabled by default, I will remove it from the release 1.0.0.0 milestone

**Comment by mattiasnordqvist** [comment]
ToDictionary has been removed as of v5.0.0.
