### ISSUE TITLE
Expose Json serialiser

### ISSUE THREAD

**Issue by mattiasnordqvist** [mattiasnordqvist/Web-Anchor#4]
Expose the json serialisers from requestbuilder and responseparser so that their settings can be reached and modified through Api.For

**Comment by mattiasnordqvist** [comment]
If I want json camelcasing today, i must do this :-1: 

```csharp
var api = Api.For<IGeckoApi>("http://localhost:1111", new HttpRequestFactory(new ContentSerializer(new JsonSerializer { ContractResolver = new CamelCasePropertyNamesContractResolver()})));
```

**Comment by carl-berg** [comment]
This is not really fixed in latest version. Id say it's worse now as you have to create a new class to set jsonserializer settings.

**Comment by carl-berg** [comment]
Can't think of a better solution right now than to either take a JsonSerializer or Action<JsonSerializer> as a constructor parameter to ApiSettings.

**Comment by mattiasnordqvist** [comment]
I think this is ok, which will be how it works in v5.0.0

```csharp
 var api = Api.For<ITypicodeApi>("http://jsonplaceholder.typicode.com", x => 
{
    x.Request.ContentSerializer = new JsonContentSerializer(new JsonSerializer { ContractResolver = new Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver() });
});
```

What do you think @carl-berg ?

**Comment by carl-berg** [comment]
Nice. Does the x (whatever type that is) have both a Request and a Response property?

**Comment by mattiasnordqvist** [comment]
Yes. 
ContentSerializer can be set through ApiSettings like this or by using [Json] or [UrlFormEncoded] together with [Content] on a parameter, or by in any other way changing it on the RequestTransformContext-object available for every request-invocation in v5.0.0.

**Comment by carl-berg** [comment]
Can the FormUrlEncoded serializer be inherited or does it need to be replaced if you for instance want to camel case it's parameters?

**Comment by mattiasnordqvist** [comment]
It has to be replaced. This hasn't changed in the last few years. :) Also, it has only one method, so inheriting it doesn't really help. It could be refactored though, to make inheritence more useful

**Comment by carl-berg** [comment]
I think it would be nice to be able to get ahold of the KeyValuePair -list (or whatever the type is) if you inherit the default serializer, but that doesn't really belong to this issue.
