### ISSUE TITLE
Come up with a nice way to pass arguments to a transformer

### ISSUE THREAD

**Issue by mattiasnordqvist** [mattiasnordqvist/Web-Anchor#40]
For example, it would be nice to be able to switch the .ToDictionary() on and off in the defaultparameterresolver, since it is an extra step not required in most scenarios

**Comment by mattiasnordqvist** [comment]
Today it is possible to do it via attributes on parameters, methods or apis. Maybe this is enough? Default settings for an api could easily be set via an attribute on the api?

**Comment by carl-berg** [comment]
Im not completely up to speed on this issue but maybe a `Dictionary<string,object> Context` that can be passed along (Owin-style)? Just an idea.

**Comment by mattiasnordqvist** [comment]
this will not be needed in v5.0.0

**Comment by mattiasnordqvist** [comment]
But I think we should allow it anyways. What about some free-for-all string->object dictionary on the requesttransformcontext?
