### ISSUE TITLE
Make return type a pluggable thing

### ISSUE THREAD

**Issue by mattiasnordqvist** [mattiasnordqvist/Web-Anchor#43]
So that a developer can choose to extend the list of supported return types. As an example, it would be nice to let the user tweak the response builder to create a plain string or a Promise-like object from the body content. The already existing response types (HttpRequestMessage and Task <T>  should of course be handled in the same way.

**Comment by mattiasnordqvist** [comment]
@carl-berg Wanna code review?

**Comment by carl-berg** [comment]
Looks great to me. I cleaned up the ApiSettings slightly in 1dac47d64bfc21bdfa2bf387a58123dff3eb4d2a

**Comment by mattiasnordqvist** [comment]
This is a BREAKING CHANGE since we no longer throw exception on setup of api if there are no responehandlers matching the return type.

**Comment by mattiasnordqvist** [comment]
Released in v2.0.29
