### ISSUE TITLE
Disable default call to ToDictionary

### ISSUE THREAD

**Issue by mattiasnordqvist** [mattiasnordqvist/Web-Anchor#44]
Let it be triggered only if an attribute AsDictionary can be found on the class, parameter, method or api.

**Comment by mattiasnordqvist** [comment]
How to handle presedence when class-level attribute is involved @carl-berg ?
What if an attribute on the type sent as content says AsDictionary() but there is an attribute on parameter, method or api-level that says AsDictionary(false)?

**Comment by carl-berg** [comment]
If we need that fine granularity i would say that if it's specified on parameter/method/api-level, that would override whatever is specified on the type, but it's not really obvious what outcome to expect in that case

**Comment by mattiasnordqvist** [comment]
So parameter type level has lowest precedence...

**Comment by mattiasnordqvist** [comment]
Released in 1.0.20

**Comment by mattiasnordqvist** [comment]
This is a breaking change for anyone using a transformer to modify body content.
