### ISSUE TITLE
NullReferenceException in ContentSerializer?

### ISSUE THREAD

**Issue by Frull** [mattiasnordqvist/Web-Anchor#46]
For some reason I'm getting a NullReferenceException in the ContentSerializer.
Don't actually know where to start debugging. Do I need to mark the parameters as `[Content]`?

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at WebAnchor.RequestFactory.ContentSerializer.Serialize(Parameter content)
   at WebAnchor.RequestFactory.HttpRequestFactory.ResolveContent(IInvocation invocation)
   at WebAnchor.RequestFactory.HttpRequestFactory.Create(IInvocation invocation)
   at WebAnchor.Anchor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IReportApiProxy.ResetLogInterval(String orderId, String assetId)
```

```c#
try
{
    var response = await _api.ResetLogInterval(orderId, assetId);
    return response;
}
catch (Exception e)
{
    _log.Error(e);
}
```
```c#
[BaseLocation("telemetry")]
public interface IReportApi
{
    [Put("reset-loginterval/{orderId}/{assetId}")]
    Task<HttpResponseMessage> ResetLogInterval(string orderId, string assetId); 
}
```

**Comment by mattiasnordqvist** [comment]
There is no separator between "telemetry" and "reset-loginternal". "/"s are not automatically inserted between the url segments. Either place a "/" at end of base location or at beginning of Put-parameter. This seems not to be the reason to why this code fails though. Which version of Web Anchor are you using? I cannot reproduce this in v1.0.21

**Comment by Frull** [comment]
v0.4.16 :-(

**Comment by Frull** [comment]
Thanks for the tip about "/" 

Was the behavior changed/decided in v1.0 to allow multiple parameters in query string for PUT and POST?
Should really upgrade to latest version.

In version 0.4.16 this could be solved by changing the interface to use the [Content] attribute. Also put the string parameter in a class.

```c#
[BaseLocation("telemetry")]
public interface IReportApi
{
    [Put("/reset-loginterval/{orderId}/reportLogInterval")]
    Task<HttpResponseMessage> ResetLogInterval(string orderId, [Content]ReportLogIntervalDto reportLogInterval);
}
```

**Comment by mattiasnordqvist** [comment]
Yes! This problem has been adressed. See #8.  @carl-berg mentions a temporary solution in the comments, in case you are unable to upgrade.
