### ISSUE TITLE
Default slash between BaseLocation and Attribute-Url (if missing)

### ISSUE THREAD

**Issue by carl-berg** [mattiasnordqvist/Web-Anchor#47]
Consider the following Api:
```
[BaseLocation("api")]
public interface MyApi
{
    [Get("employee/{id}"]
    Task<People> Employee(int id);
}
```
A call to fetch an employee number 5 using this api would make the following request:
`GET apiemployee/5`
I would argue that in at least 9 out of 10 cases you want the url to be `api/employee/5` and it would be helpful to provide the extra slash by default, since it might be an easy detail to forget. 

In the case where you don't want that and you want the two string to just be concatenated, a setting could be provided to turn off the default-slash behavior.

**Comment by mattiasnordqvist** [comment]
Released in v2.0.29
