### ISSUE TITLE
Restructure Wiki

### ISSUE THREAD

**Issue by mattiasnordqvist** [mattiasnordqvist/Web-Anchor#65]
I think we maybe should restructure the Wiki a bit.
"Features" and "Digging deep" sections are kind of overlapping. ("Get started" is too, but I think that is Ok.) Maybe we should split into sections something like this instead:
1. Url creation
2. Query string parameters
3. Headers
4. Request content serialization
5. Response content deserialization

And we should maybe also have some kind of documentation on the publicly available api, attributes and transformers etc. etc.

**Comment by carl-berg** [comment]
:+1: for this.
