### ISSUE TITLE
Build server and versioning

### ISSUE THREAD

**Issue by mattiasnordqvist** [mattiasnordqvist/Web-Anchor#7]

**Comment by mattiasnordqvist** [comment]
I created a teamcity build configuration hosted on spinits servers. It builds on push to develop. This will have to do for now, unitl codebetter respond to our request.

**Comment by mattiasnordqvist** [comment]
Forgot about the versioning part

**Comment by mattiasnordqvist** [comment]
Might just open source my versioning package or something to get automatic assembly+build-versioning

**Comment by carl-berg** [comment]
Done?
