### ISSUE TITLE
Find a way to use headers in content de-serialization

### ISSUE THREAD

**Issue by carl-berg** [mattiasnordqvist/Web-Anchor#9]
A use case for the is when content is returned from for instance a **POST** togeather with a location header. 
A potential idea is to decorate a property in the response-class with something like this `[Header("location")]` and have the content deserializer fill this property.

**Comment by mattiasnordqvist** [comment]
This can be done by supplying your own ContentDeserializer inheriting from the default one. I have created a test to make an example. However, this type of header retrieval could be a feature implemented in the default handler.
