### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by mattiasnordqvist** [mattiasnordqvist/Web-Anchor#93]
@all-contributors please add @carl-berg for ideas, code and review

**Comment by mattiasnordqvist** [comment]
@all-contributors please add @carl-berg for ideas, code and review

**Comment by mattiasnordqvist** [comment]
@all-contributors please add @carl-berg for ideas, code and review

**Comment by mattiasnordqvist** [comment]
@all-contributors please add @carl-berg for ideas, code and review

**Comment by mattiasnordqvist** [comment]
amen

**Comment by mattiasnordqvist** [comment]
@all-contributors please add @carl-berg for ideas, code and review

**Comment by mattiasnordqvist** [comment]
@all-contributors please add @carl-berg for ideas, code and review

**Comment by mattiasnordqvist** [comment]
@all-contributors please add @carl-berg for ideas, code and review

**Comment by mattiasnordqvist** [comment]
whats your problem?

**Comment by mattiasnordqvist** [comment]
@all-contributors please add @carl-berg for ideas, code and review

**Comment by mattiasnordqvist** [comment]
@all-contributors please add @carl-berg for ideas, code and review

**Comment by mattiasnordqvist** [comment]
how nice of you! Thank you!

**Comment by teamcoltra** [comment]
... I really like this thread...
